# render.yaml
services:
  - type: web
    name: currency-converter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: EXCHANGE_RATE_API_KEY  
        sync: false # Esto significa que lo configurarás manualmente en Render Secrets